import {
  TOKEN_CONTRACT_METHODS,
  DISTRIBUTION_CONTRACT_METHODS,
  L1_SENDER_CONTRACT_METHODS,
  L2_MESSAGE_RECEIVER_CONTRACT_METHODS,
  L2_TOKEN_RECEIVER_CONTRACT_METHODS,
} from '@/enums'

export const CONTRACT_METHODS = {
  ...TOKEN_CONTRACT_METHODS,
  ...DISTRIBUTION_CONTRACT_METHODS,
  ...L1_SENDER_CONTRACT_METHODS,
  ...L2_MESSAGE_RECEIVER_CONTRACT_METHODS,
  ...L2_TOKEN_RECEIVER_CONTRACT_METHODS,
}
