export enum ICON_NAMES {
  arbitrumAlt = 'arbitrum-alt',
  arbitrum = 'arbitrum',
  arrowLeft = 'arrow-left',
  calendar = 'calendar',
  checkCircle = 'check-circle',
  check = 'check',
  chevronDown = 'chevron-down',
  copy = 'copy',
  edit = 'edit',
  ethereumAlt = 'ethereum-alt',
  ethereum = 'ethereum',
  exclamationCircle = 'exclamation-circle',
  externalLink = 'external-link',
  eyeOff = 'eye-off',
  eye = 'eye',
  menuAlt1 = 'menu-alt-1',
  morpheus = 'morpheus',
  save = 'save',
  steth = 'steth',
  trash = 'trash',
  xCircle = 'x-circle',
  x = 'x',
}
