export enum ICON_NAMES {
  arbitrum = 'arbitrum',
  calendar = 'calendar',
  checkCircle = 'check-circle',
  check = 'check',
  chevronDown = 'chevron-down',
  copy = 'copy',
  ethereum = 'ethereum',
  exclamationCircle = 'exclamation-circle',
  externalLink = 'external-link',
  eyeOff = 'eye-off',
  eye = 'eye',
  menuAlt1 = 'menu-alt-1',
  morpheus = 'morpheus',
  steth = 'steth',
  xCircle = 'x-circle',
  x = 'x',
}
