export enum ICON_NAMES {
  arbitrumAlt1 = 'arbitrum-alt-1',
  arbitrum = 'arbitrum',
  checkCircle = 'check-circle',
  chevronDown = 'chevron-down',
  ethereumAlt1 = 'ethereum-alt-1',
  ethereum = 'ethereum',
  exclamationCircle = 'exclamation-circle',
  externalLink = 'external-link',
  eyeOff = 'eye-off',
  eye = 'eye',
  menuAlt1 = 'menu-alt-1',
  morpheus = 'morpheus',
  steth = 'steth',
  xCircle = 'x-circle',
  x = 'x',
}
