/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace IL2TokenReceiver {
  export type SwapParamsStruct = {
    tokenIn: string;
    tokenOut: string;
    fee: BigNumberish;
  };

  export type SwapParamsStructOutput = [string, string, number] & {
    tokenIn: string;
    tokenOut: string;
    fee: number;
  };
}

export declare namespace IL2Factory {
  export type L2ParamsStruct = {
    isUpgradeable: boolean;
    owner: string;
    protocolName: string;
    mor20Name: string;
    mor20Symbol: string;
    l1Sender: string;
    firstSwapParams_: IL2TokenReceiver.SwapParamsStruct;
    secondSwapFee: BigNumberish;
  };

  export type L2ParamsStructOutput = [
    boolean,
    string,
    string,
    string,
    string,
    string,
    IL2TokenReceiver.SwapParamsStructOutput,
    number
  ] & {
    isUpgradeable: boolean;
    owner: string;
    protocolName: string;
    mor20Name: string;
    mor20Symbol: string;
    l1Sender: string;
    firstSwapParams_: IL2TokenReceiver.SwapParamsStructOutput;
    secondSwapFee: number;
  };

  export type PoolViewStruct = {
    protocol: string;
    l2MessageReceiver: string;
    l2TokenReceiver: string;
    mor20: string;
  };

  export type PoolViewStructOutput = [string, string, string, string] & {
    protocol: string;
    l2MessageReceiver: string;
    l2TokenReceiver: string;
    mor20: string;
  };

  export type LzExternalDepsStruct = {
    endpoint: string;
    oftEndpoint: string;
    senderChainId: BigNumberish;
  };

  export type LzExternalDepsStructOutput = [string, string, number] & {
    endpoint: string;
    oftEndpoint: string;
    senderChainId: number;
  };

  export type UniswapExternalDepsStruct = {
    router: string;
    nonfungiblePositionManager: string;
  };

  export type UniswapExternalDepsStructOutput = [string, string] & {
    router: string;
    nonfungiblePositionManager: string;
  };
}

export interface L2FactoryInterface extends utils.Interface {
  functions: {
    "L2Factory_init()": FunctionFragment;
    "L2_MESSAGE_RECEIVER_POOL()": FunctionFragment;
    "L2_TOKEN_RECEIVER_POOL()": FunctionFragment;
    "countProtocols(address)": FunctionFragment;
    "deploy((bool,address,string,string,string,address,(address,address,uint24),uint24))": FunctionFragment;
    "freezePool(string,string)": FunctionFragment;
    "getBeacon(string)": FunctionFragment;
    "getDeployedPools(address,uint256,uint256)": FunctionFragment;
    "getImplementation(string)": FunctionFragment;
    "getMor20(address,string)": FunctionFragment;
    "getProxyPool(address,string,string)": FunctionFragment;
    "listProtocols(address,uint256,uint256)": FunctionFragment;
    "lzExternalDeps()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "predictAddresses(address,string)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setImplementations(string[],address[])": FunctionFragment;
    "setLzExternalDeps((address,address,uint16))": FunctionFragment;
    "setUniswapExternalDeps((address,address))": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unfreezePool(string,string)": FunctionFragment;
    "uniswapExternalDeps()": FunctionFragment;
    "unpause()": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "L2Factory_init"
      | "L2_MESSAGE_RECEIVER_POOL"
      | "L2_TOKEN_RECEIVER_POOL"
      | "countProtocols"
      | "deploy"
      | "freezePool"
      | "getBeacon"
      | "getDeployedPools"
      | "getImplementation"
      | "getMor20"
      | "getProxyPool"
      | "listProtocols"
      | "lzExternalDeps"
      | "owner"
      | "pause"
      | "paused"
      | "predictAddresses"
      | "proxiableUUID"
      | "renounceOwnership"
      | "setImplementations"
      | "setLzExternalDeps"
      | "setUniswapExternalDeps"
      | "transferOwnership"
      | "unfreezePool"
      | "uniswapExternalDeps"
      | "unpause"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "L2Factory_init",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L2_MESSAGE_RECEIVER_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L2_TOKEN_RECEIVER_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "countProtocols",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deploy",
    values: [IL2Factory.L2ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "freezePool",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "getBeacon", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getDeployedPools",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMor20",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProxyPool",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "listProtocols",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lzExternalDeps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictAddresses",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementations",
    values: [string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setLzExternalDeps",
    values: [IL2Factory.LzExternalDepsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setUniswapExternalDeps",
    values: [IL2Factory.UniswapExternalDepsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezePool",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapExternalDeps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "L2Factory_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "L2_MESSAGE_RECEIVER_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "L2_TOKEN_RECEIVER_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "countProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "freezePool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBeacon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMor20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProxyPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lzExternalDeps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLzExternalDeps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUniswapExternalDeps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapExternalDeps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "ProxyDeployed(address,address,string,string)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProxyDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface ProxyDeployedEventObject {
  proxy: string;
  implementation: string;
  protocol: string;
  poolType: string;
}
export type ProxyDeployedEvent = TypedEvent<
  [string, string, string, string],
  ProxyDeployedEventObject
>;

export type ProxyDeployedEventFilter = TypedEventFilter<ProxyDeployedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface L2Factory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L2FactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    L2Factory_init(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    L2_MESSAGE_RECEIVER_POOL(overrides?: CallOverrides): Promise<[string]>;

    L2_TOKEN_RECEIVER_POOL(overrides?: CallOverrides): Promise<[string]>;

    countProtocols(
      deployer_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deploy(
      l2Params_: IL2Factory.L2ParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    freezePool(
      protocol_: string,
      poolType_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBeacon(poolType_: string, overrides?: CallOverrides): Promise<[string]>;

    getDeployedPools(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [IL2Factory.PoolViewStructOutput[]] & {
        pools_: IL2Factory.PoolViewStructOutput[];
      }
    >;

    getImplementation(
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMor20(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getProxyPool(
      deployer_: string,
      protocol_: string,
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    listProtocols(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { protocols_: string[] }>;

    lzExternalDeps(
      overrides?: CallOverrides
    ): Promise<
      [string, string, number] & {
        endpoint: string;
        oftEndpoint: string;
        senderChainId: number;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    predictAddresses(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & {
        l2MessageReceiver_: string;
        l2TokenReceiver_: string;
      }
    >;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setImplementations(
      poolTypes_: string[],
      implementations_: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setLzExternalDeps(
      lzExternalDeps_: IL2Factory.LzExternalDepsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUniswapExternalDeps(
      uniswapExternalDeps_: IL2Factory.UniswapExternalDepsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unfreezePool(
      protocol_: string,
      poolType_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    uniswapExternalDeps(
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { router: string; nonfungiblePositionManager: string }
    >;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  L2Factory_init(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  L2_MESSAGE_RECEIVER_POOL(overrides?: CallOverrides): Promise<string>;

  L2_TOKEN_RECEIVER_POOL(overrides?: CallOverrides): Promise<string>;

  countProtocols(
    deployer_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deploy(
    l2Params_: IL2Factory.L2ParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  freezePool(
    protocol_: string,
    poolType_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBeacon(poolType_: string, overrides?: CallOverrides): Promise<string>;

  getDeployedPools(
    deployer_: string,
    offset_: BigNumberish,
    limit_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IL2Factory.PoolViewStructOutput[]>;

  getImplementation(
    poolType_: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getMor20(
    deployer_: string,
    protocol_: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getProxyPool(
    deployer_: string,
    protocol_: string,
    poolType_: string,
    overrides?: CallOverrides
  ): Promise<string>;

  listProtocols(
    deployer_: string,
    offset_: BigNumberish,
    limit_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  lzExternalDeps(
    overrides?: CallOverrides
  ): Promise<
    [string, string, number] & {
      endpoint: string;
      oftEndpoint: string;
      senderChainId: number;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  predictAddresses(
    deployer_: string,
    protocol_: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string] & { l2MessageReceiver_: string; l2TokenReceiver_: string }
  >;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setImplementations(
    poolTypes_: string[],
    implementations_: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setLzExternalDeps(
    lzExternalDeps_: IL2Factory.LzExternalDepsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUniswapExternalDeps(
    uniswapExternalDeps_: IL2Factory.UniswapExternalDepsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unfreezePool(
    protocol_: string,
    poolType_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  uniswapExternalDeps(
    overrides?: CallOverrides
  ): Promise<
    [string, string] & { router: string; nonfungiblePositionManager: string }
  >;

  unpause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    L2Factory_init(overrides?: CallOverrides): Promise<void>;

    L2_MESSAGE_RECEIVER_POOL(overrides?: CallOverrides): Promise<string>;

    L2_TOKEN_RECEIVER_POOL(overrides?: CallOverrides): Promise<string>;

    countProtocols(
      deployer_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deploy(
      l2Params_: IL2Factory.L2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    freezePool(
      protocol_: string,
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getBeacon(poolType_: string, overrides?: CallOverrides): Promise<string>;

    getDeployedPools(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IL2Factory.PoolViewStructOutput[]>;

    getImplementation(
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getMor20(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getProxyPool(
      deployer_: string,
      protocol_: string,
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    listProtocols(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    lzExternalDeps(
      overrides?: CallOverrides
    ): Promise<
      [string, string, number] & {
        endpoint: string;
        oftEndpoint: string;
        senderChainId: number;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    predictAddresses(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & {
        l2MessageReceiver_: string;
        l2TokenReceiver_: string;
      }
    >;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setImplementations(
      poolTypes_: string[],
      implementations_: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setLzExternalDeps(
      lzExternalDeps_: IL2Factory.LzExternalDepsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setUniswapExternalDeps(
      uniswapExternalDeps_: IL2Factory.UniswapExternalDepsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unfreezePool(
      protocol_: string,
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapExternalDeps(
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { router: string; nonfungiblePositionManager: string }
    >;

    unpause(overrides?: CallOverrides): Promise<void>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(beacon?: string | null): BeaconUpgradedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "ProxyDeployed(address,address,string,string)"(
      proxy?: null,
      implementation?: string | null,
      protocol?: null,
      poolType?: null
    ): ProxyDeployedEventFilter;
    ProxyDeployed(
      proxy?: null,
      implementation?: string | null,
      protocol?: null,
      poolType?: null
    ): ProxyDeployedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    L2Factory_init(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    L2_MESSAGE_RECEIVER_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    L2_TOKEN_RECEIVER_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    countProtocols(
      deployer_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deploy(
      l2Params_: IL2Factory.L2ParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    freezePool(
      protocol_: string,
      poolType_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBeacon(poolType_: string, overrides?: CallOverrides): Promise<BigNumber>;

    getDeployedPools(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getImplementation(
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMor20(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProxyPool(
      deployer_: string,
      protocol_: string,
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listProtocols(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lzExternalDeps(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    predictAddresses(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setImplementations(
      poolTypes_: string[],
      implementations_: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setLzExternalDeps(
      lzExternalDeps_: IL2Factory.LzExternalDepsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setUniswapExternalDeps(
      uniswapExternalDeps_: IL2Factory.UniswapExternalDepsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    unfreezePool(
      protocol_: string,
      poolType_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    uniswapExternalDeps(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    L2Factory_init(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    L2_MESSAGE_RECEIVER_POOL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    L2_TOKEN_RECEIVER_POOL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    countProtocols(
      deployer_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deploy(
      l2Params_: IL2Factory.L2ParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    freezePool(
      protocol_: string,
      poolType_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBeacon(
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeployedPools(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getImplementation(
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMor20(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProxyPool(
      deployer_: string,
      protocol_: string,
      poolType_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listProtocols(
      deployer_: string,
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lzExternalDeps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    predictAddresses(
      deployer_: string,
      protocol_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setImplementations(
      poolTypes_: string[],
      implementations_: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setLzExternalDeps(
      lzExternalDeps_: IL2Factory.LzExternalDepsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUniswapExternalDeps(
      uniswapExternalDeps_: IL2Factory.UniswapExternalDepsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unfreezePool(
      protocol_: string,
      poolType_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    uniswapExternalDeps(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
