/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Builders, BuildersInterface } from "../Builders";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "previousAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "AdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "builderPool",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "AdminClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beacon",
        type: "address",
      },
    ],
    name: "BeaconUpgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "builderPoolId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "address",
            name: "admin",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "poolStart",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "withdrawLockPeriodAfterDeposit",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "claimLockEnd",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "minimalDeposit",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct IBuilders.BuilderPool",
        name: "builderPool",
        type: "tuple",
      },
    ],
    name: "BuilderPoolCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "builderPoolId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "address",
            name: "admin",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "poolStart",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "withdrawLockPeriodAfterDeposit",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "claimLockEnd",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "minimalDeposit",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct IBuilders.BuilderPool",
        name: "builderPool",
        type: "tuple",
      },
    ],
    name: "BuilderPoolEdited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "buildersTreasury",
        type: "address",
      },
    ],
    name: "BuildersTreasurySet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint128",
        name: "editPoolDeadline",
        type: "uint128",
      },
    ],
    name: "EditPoolDeadlineSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "feeConfig",
        type: "address",
      },
    ],
    name: "FeeConfigSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "operation",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "treasury",
        type: "address",
      },
    ],
    name: "FeePaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "minimalWithdrawLockPeriod",
        type: "uint256",
      },
    ],
    name: "MinimalWithdrawLockPeriodSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "builderPool",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "UserDeposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "builderPool",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "UserWithdrawn",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "depositToken_",
        type: "address",
      },
      {
        internalType: "address",
        name: "feeConfig_",
        type: "address",
      },
      {
        internalType: "address",
        name: "buildersTreasury_",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "editPoolDeadline_",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "minimalWithdrawLockPeriod_",
        type: "uint256",
      },
    ],
    name: "Builders_init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "builderPoolId",
        type: "bytes32",
      },
    ],
    name: "builderPools",
    outputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "poolStart",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "withdrawLockPeriodAfterDeposit",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "claimLockEnd",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "minimalDeposit",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "builderPoolId",
        type: "bytes32",
      },
    ],
    name: "buildersPoolData",
    outputs: [
      {
        internalType: "uint128",
        name: "lastDeposit",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "virtualDeposited",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pendingRewards",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "buildersTreasury",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "builderPoolId_",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "receiver_",
        type: "address",
      },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "address",
            name: "admin",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "poolStart",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "withdrawLockPeriodAfterDeposit",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "claimLockEnd",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "minimalDeposit",
            type: "uint256",
          },
        ],
        internalType: "struct IBuilders.BuilderPool",
        name: "builderPool_",
        type: "tuple",
      },
    ],
    name: "createBuilderPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "builderPoolId_",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "address",
            name: "admin",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "poolStart",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "withdrawLockPeriodAfterDeposit",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "claimLockEnd",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "minimalDeposit",
            type: "uint256",
          },
        ],
        internalType: "struct IBuilders.BuilderPool",
        name: "builderPool_",
        type: "tuple",
      },
    ],
    name: "editBuilderPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "editPoolDeadline",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeConfig",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "builderPoolId_",
        type: "bytes32",
      },
    ],
    name: "getCurrentBuilderReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "builderPoolId_",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "user_",
        type: "address",
      },
    ],
    name: "getCurrentUserMultiplier",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "lockStart_",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "lockEnd_",
        type: "uint128",
      },
    ],
    name: "getLockPeriodMultiplier",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getNotDistributedRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "builderPoolName_",
        type: "string",
      },
    ],
    name: "getPoolId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "minimalWithdrawLockPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "buildersTreasury_",
        type: "address",
      },
    ],
    name: "setBuildersTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "editPoolDeadline_",
        type: "uint128",
      },
    ],
    name: "setEditPoolDeadline",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "feeConfig_",
        type: "address",
      },
    ],
    name: "setFeeConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minimalWithdrawLockPeriod_",
        type: "uint256",
      },
    ],
    name: "setMinimalWithdrawLockPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId_",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPoolData",
    outputs: [
      {
        internalType: "uint256",
        name: "distributedRewards",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalVirtualDeposited",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
    ],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "builderPoolId",
        type: "bytes32",
      },
    ],
    name: "usersData",
    outputs: [
      {
        internalType: "uint128",
        name: "lastDeposit",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "claimLockStart",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "deposited",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "virtualDeposited",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "builderPoolId_",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Builders__factory {
  static readonly abi = _abi;
  static createInterface(): BuildersInterface {
    return new utils.Interface(_abi) as BuildersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Builders {
    return new Contract(address, _abi, signerOrProvider) as Builders;
  }
}
